service: isaac
image: ghcr.io/mjc-gh/isaac
builder:
  arch:
    - amd64
    - arm64
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

aliases:
  release: deploy --skip-push --version "sha-$(git rev-parse --short HEAD)"
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

env:
  secret:
    - SECRET_KEY_BASE
    - OPENROUTER_API_KEY
    - SMTP_ADDRESS
    - SMTP_DOMAIN
    - SMTP_USER_NAME
    - SMTP_PASSWORD

servers:
  web:
    hosts:
      - <%= ENV.fetch("KAMAL_WEB_HOST") %>

volumes:
  - "<%= ENV.fetch("KAMAL_VOLUME_PATH") %>:/rails/storage"
