service: isaac
image: ghcr.io/mjc-gh/isaac
servers:
  web:
    hosts:
      - <%= ENV.fetch("KAMAL_WEB_HOST"] %>
registry:
  server: ghcr.io
  username: mjc-gh
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - SECRET_KEY_BASE
    - OPENROUTER_API_KEY
    - STMP_ADDRESS
    - STMP_DOMAIN
    - STMP_USERNAME
    - STMP_PASSWORD

aliases:
  release: deploy --skip-push --version "sha-$(git rev-parse --short HEAD)"
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "<%= ENV.fetch("KAMAL_VOLUME_PATH") %>:/rails/storage"
